# Generated by Django 3.2.9 on 2021-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('Article', 'article'), ('Status', 'status'), ('Reply', 'in-reply-to'), ('RSVP', 'rsvp'), ('Like', 'like-of'), ('Bookmark', 'bookmark'), ('Check - in', 'checkin'), ('Repost', 'repost-of'), ('Photo', 'photo'), ('Sport', 'sport')], default='Article', max_length=13),
        ),
    ]
