# Generated by Django 3.2.9 on 2021-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('article', 'article'), ('status', 'status'), ('in-reply-to', 'in-reply-to'), ('rsvp', 'rsvp'), ('like-of', 'like-of'), ('bookmark', 'bookmark'), ('checkin', 'checkin'), ('repost-of', 'repost-of'), ('photo', 'photo'), ('sport', 'sport')], default='article', max_length=13),
        ),
    ]
