# Generated by Django 3.2.9 on 2021-11-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_indiewebsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.indiewebsource'),
        ),
    ]
