# Generated by Django 3.2.9 on 2021-12-13 08:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.indiewebkind'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='webMention',
            field=models.URLField(blank=True, default='', verbose_name='Webmention target'),
        ),
    ]
