# Generated by Django 3.2.9 on 2021-12-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_post_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.indiewebkind'),
        ),
    ]
